Construct qubit layouts with Quantum (Qiskit) Metal and mesh with pyPalace (Gmsh backend)

In [1]:
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, open_docs
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross
from qiskit_metal.toolbox_python.attr_dict import Dict
from qiskit_metal.qlibrary.core import QComponent
from qiskit_metal.qlibrary.qubits.transmon_pocket import TransmonPocket

In [2]:
from pypalace import mesh

## Pocket (double pad) Transmon

In [3]:
design = designs.DesignPlanar()
gui = MetalGUI(design)

gui = MetalGUI(design)

# Double-pad qubit (TransmonPocket)
qubit = TransmonPocket(design,
                       "pocket_transmon",
                        
                        # qubit options
                       options=Dict( 
                            pos_x="0mm",
                            pos_y="0mm",
                            orientation="0",
                            pad_width="500um",
                            pad_height="125um",
                            pocket_width="1200um",
                            pocket_height="1200um",
                            pad_gap="30um",
                            # we don't need the quasi-junction for electrostatic / capacitance simulations.
                            inductor_width="0um",
                            
                        # coupler options
                        connection_pads=Dict(
                            readout=Dict(
                                pad_width="143um",
                                pad_height="47um",
                                pad_gap="25um",
                                loc_W = -1,
                                loc_H = +1))))

cpw_width = 0
cpw_gap = 0
cpw_extend = 0
pad_cpw_extent = 0


gui.rebuild()
gui.autoscale()

In [4]:
design.qgeometry.tables["poly"]

,component,name,geometry,layer,subtract,helper,chip,fillet
0,1,pad_top,"POLYGON ((-0.25 0.015, 0.25 0.015, 0.25 0.14, ...",1,False,False,main,NaN
1,1,pad_bot,"POLYGON ((-0.25 -0.14, 0.25 -0.14, 0.25 -0.015...",1,False,False,main,NaN
2,1,rect_pk,"POLYGON ((-0.6 -0.6, 0.6 -0.6, 0.6 0.6, -0.6 0...",1,True,False,main,NaN
3,1,readout_connector_pad,"POLYGON ((-0.107 0.165, -0.25 0.165, -0.25 0.2...",1,False,False,main,NaN

In [5]:
''' Mesh our Quantum Metal design '''

## define which components we want to give mesh attributes ##
Attributes = {"pad_top":1,"pad_bot":2,"readout_connector_pad":3}

mesh_dir = "mesh/"
meshfile = "pocket_transmon.msh"
path_to_mesh = mesh_dir + meshfile

## mesh the design --> returns pandas.dataframe of labeled mesh attributes ##
## look at readthedocs, mesh_Quantum_Metal_design has a lot of flexibility to control surface mesh size, volume mesh size, substrate size, etc ## 
attributes_table = mesh.mesh_Quantum_Metal_design(design,output_mesh=path_to_mesh,Attributes=Attributes,surface_mesh_size=0.0005);

Info    : Meshing 1D...nts
Info    : [  0%] Meshing curve 25 (Line)
Info    : [ 10%] Meshing curve 26 (Line)
Info    : [ 10%] Meshing curve 27 (Line)
Info    : [ 10%] Meshing curve 28 (Line)
Info    : [ 20%] Meshing curve 29 (Line)
Info    : [ 20%] Meshing curve 30 (Line)
Info    : [ 20%] Meshing curve 31 (Line)
Info    : [ 20%] Meshing curve 32 (Line)
Info    : [ 30%] Meshing curve 37 (Line)
Info    : [ 30%] Meshing curve 38 (Line)
Info    : [ 30%] Meshing curve 39 (Line)
Info    : [ 40%] Meshing curve 40 (Line)
Info    : [ 40%] Meshing curve 41 (Line)
Info    : [ 40%] Meshing curve 42 (Line)
Info    : [ 40%] Meshing curve 43 (Line)
Info    : [ 50%] Meshing curve 44 (Line)
Info    : [ 50%] Meshing curve 45 (Line)
Info    : [ 50%] Meshing curve 46 (Line)
Info    : [ 60%] Meshing curve 47 (Line)
Info    : [ 60%] Meshing curve 48 (Line)
Info    : [ 60%] Meshing curve 49 (Line)
Info    : [ 60%] Meshing curve 50 (Line)
Info    : [ 70%] Meshing curve 51 (Line)
Info    : [ 70%] Meshing curve 52 (Line)
Info    : [ 70%] Meshing curve 53 (Line)
Info    : [ 70%] Meshing curve 54 (Line)
Info    : [ 80%] Meshing curve 55 (Line)
Info    : [ 80%] Meshing curve 56 (Line)
Info    : [ 80%] Meshing curve 57 (Line)
Info    : [ 90%] Meshing curve 58 (Line)
Info    : [ 90%] Meshing curve 59 (Line)
Info    : [ 90%] Meshing curve 60 (Line)
Info    : [ 90%] Meshing curve 61 (Line)
Info    : [100%] Meshing curve 62 (Line)
Info    : [100%] Meshing curve 63 (Line)
Info    : [100%] Meshing curve 64 (Line)
Info    : Done meshing 1D (Wall 2.91189s, CPU 2.87806s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 13 (Plane, Frontal-Delaunay)
Info    : [ 10%] Meshing surface 14 (Plane, Frontal-Delaunay)
Info    : [ 20%] Meshing surface 16 (Plane, Frontal-Delaunay)
Info    : [ 30%] Meshing surface 17 (Plane, Frontal-Delaunay)
Info    : [ 30%] Meshing surface 18 (Plane, Frontal-Delaunay)
Info    : [ 40%] Meshing surface 19 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 20 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 21 (Plane, Frontal-Delaunay)
Info    : [ 60%] Meshing surface 22 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 23 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 24 (Plane, Frontal-Delaunay)
Info    : [ 80%] Meshing surface 25 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 26 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 27 (Plane, Frontal-Delaunay)
Info    : [100%] Meshing surface 28 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 2.27321s, CPU 2.25233s)
Info    : Meshing 3D...
Info    : 3D Meshing 2 volumes with 1 connected component
Info    : Tetrahedrizing 69994 nodes...
Info    : Done tetrahedrizing 70002 nodes (Wall 5.64828s, CPU 5.60367s)
Info    : Reconstructing mesh...
Info    :  - Creating surface mesh
Info    :  - Identifying boundary edges
Info    :  - Recovering boundary
Info    : Done reconstructing mesh (Wall 8.75396s, CPU 8.63354s)
Info    : Found volume 2
Info    : Found volume 1
Info    : It. 0 - 0 nodes created - worst tet radius 9.89373 (nodes removed 0 0)
Info    : It. 500 - 500 nodes created - worst tet radius 2.77459 (nodes removed 0 0)
Info    : It. 1000 - 1000 nodes created - worst tet radius 1.99222 (nodes removed 0 0)
Info    : It. 1500 - 1500 nodes created - worst tet radius 1.91372 (nodes removed 0 0)
Info    : It. 2000 - 2000 nodes created - worst tet radius 1.72849 (nodes removed 0 0)
Info    : It. 2500 - 2500 nodes created - worst tet radius 1.78341 (nodes removed 0 0)
Info    : It. 3000 - 3000 nodes created - worst tet radius 1.50301 (nodes removed 0 0)
Info    : It. 3500 - 3500 nodes created - worst tet radius 1.47625 (nodes removed 0 0)
Info    : It. 4000 - 4000 nodes created - worst tet radius 1.80272 (nodes removed 0 0)
Info    : It. 4500 - 4500 nodes created - worst tet radius 1.41707 (nodes removed 0 0)
Info    : It. 5000 - 5000 nodes created - worst tet radius 1.59865 (nodes removed 0 0)
Info    : It. 5500 - 5500 nodes created - worst tet radius 1.36266 (nodes removed 0 0)
Info    : It. 6000 - 6000 nodes created - worst tet radius 1.39125 (nodes removed 0 0)
Info    : It. 6500 - 6500 nodes created - worst tet radius 1.32637 (nodes removed 0 0)
Info    : It. 7000 - 7000 nodes created - worst tet radius 1.31399 (nodes removed 0 0)
Info    : It. 7500 - 7500 nodes created - worst tet radius 1.4036 (nodes removed 0 0)
Info    : It. 8000 - 8000 nodes created - worst tet radius 1.62895 (nodes removed 0 0)
Info    : It. 8500 - 8500 nodes created - worst tet radius 1.26915 (nodes removed 0 0)
Info    : It. 9000 - 9000 nodes created - worst tet radius 1.25466 (nodes removed 0 0)
Info    : It. 9500 - 9500 nodes created - worst tet radius 1.30093 (nodes removed 0 0)
Info    : It. 10000 - 10000 nodes created - worst tet radius 1.22701 (nodes removed 0 0)
Info    : It. 10500 - 10500 nodes created - worst tet radius 1.21534 (nodes removed 0 0)
Info    : It. 11000 - 11000 nodes created - worst tet radius 1.28294 (nodes removed 0 0)
Info    : It. 11500 - 11500 nodes created - worst tet radius 1.19128 (nodes removed 0 0)
Info    : It. 12000 - 12000 nodes created - worst tet radius 1.21846 (nodes removed 0 0)
Info    : It. 12500 - 12500 nodes created - worst tet radius 1.16896 (nodes removed 0 0)
Info    : It. 13000 - 13000 nodes created - worst tet radius 1.15884 (nodes removed 0 0)
Info    : It. 13500 - 13500 nodes created - worst tet radius 1.15116 (nodes removed 0 0)
Info    : It. 14000 - 14000 nodes created - worst tet radius 1.14175 (nodes removed 0 0)
Info    : It. 14500 - 14500 nodes created - worst tet radius 1.12993 (nodes removed 0 0)
Info    : It. 15000 - 15000 nodes created - worst tet radius 1.25383 (nodes removed 0 0)
Info    : It. 15500 - 15500 nodes created - worst tet radius 1.11155 (nodes removed 0 0)
Info    : It. 16000 - 16000 nodes created - worst tet radius 1.104 (nodes removed 0 0)
Info    : It. 16500 - 16500 nodes created - worst tet radius 1.10163 (nodes removed 0 0)
Info    : It. 17000 - 17000 nodes created - worst tet radius 1.14923 (nodes removed 0 0)
Info    : It. 17500 - 17500 nodes created - worst tet radius 1.08248 (nodes removed 0 0)
Info    : It. 18000 - 18000 nodes created - worst tet radius 1.18403 (nodes removed 0 0)
Info    : It. 18500 - 18500 nodes created - worst tet radius 1.12442 (nodes removed 0 0)
Info    : It. 19000 - 19000 nodes created - worst tet radius 1.07954 (nodes removed 0 0)
Info    : It. 19500 - 19500 nodes created - worst tet radius 1.05109 (nodes removed 0 0)
Info    : It. 20000 - 20000 nodes created - worst tet radius 1.25916 (nodes removed 0 0)
Info    : It. 20500 - 20500 nodes created - worst tet radius 1.14375 (nodes removed 0 0)
Info    : It. 21000 - 21000 nodes created - worst tet radius 1.03337 (nodes removed 0 0)
Info    : It. 21500 - 21500 nodes created - worst tet radius 1.05244 (nodes removed 0 0)
Info    : It. 22000 - 22000 nodes created - worst tet radius 1.03138 (nodes removed 0 0)
Info    : It. 22500 - 22500 nodes created - worst tet radius 1.07988 (nodes removed 0 0)
Info    : It. 23000 - 23000 nodes created - worst tet radius 1.109 (nodes removed 0 0)
Info    : It. 23500 - 23500 nodes created - worst tet radius 1.00146 (nodes removed 0 0)
Info    : 3D refinement terminated (93646 nodes total):
Info    :  - 90 Delaunay cavities modified for star shapeness
Info    :  - 0 nodes could not be inserted
Info    :  - 503544 tetrahedra created in 7.85934 sec. (64069 tets/s)
Info    : 4436 node relocations
Info    : Done meshing 3D (Wall 19.6002s, CPU 19.2564s)
Info    : Optimizing mesh...
Info    : Optimizing volume 1
Info    : Optimization starts (volume = 2.42e+09) with worst = 0.00039453 / average = 0.51064:
Info    : 0.00 < quality < 0.10 :      2572 elements
Info    : 0.10 < quality < 0.20 :      8138 elements
Info    : 0.20 < quality < 0.30 :     18634 elements
Info    : 0.30 < quality < 0.40 :     47497 elements
Info    : 0.40 < quality < 0.50 :     59788 elements
Info    : 0.50 < quality < 0.60 :     43651 elements
Info    : 0.60 < quality < 0.70 :     24015 elements
Info    : 0.70 < quality < 0.80 :     19244 elements
Info    : 0.80 < quality < 0.90 :     18710 elements
Info    : 0.90 < quality < 1.00 :      9534 elements
Info    : 8587 edge swaps, 2812 node relocations (volume = 2.42e+09): worst = 0.0329135 / average = 0.524533 (Wall 0.728295s, CPU 0.721051s)
Info    : 9785 edge swaps, 3902 node relocations (volume = 2.42e+09): worst = 0.0329135 / average = 0.52507 (Wall 1.33408s, CPU 1.32142s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :      1153 elements
Info    : 0.10 < quality < 0.20 :      4740 elements
Info    : 0.20 < quality < 0.30 :     12595 elements
Info    : 0.30 < quality < 0.40 :     47021 elements
Info    : 0.40 < quality < 0.50 :     58990 elements
Info    : 0.50 < quality < 0.60 :     44621 elements
Info    : 0.60 < quality < 0.70 :     24920 elements
Info    : 0.70 < quality < 0.80 :     19512 elements
Info    : 0.80 < quality < 0.90 :     18985 elements
Info    : 0.90 < quality < 1.00 :      9633 elements
Info    : Optimizing volume 2
Info    : Optimization starts (volume = 2.42e+09) with worst = 0.00039453 / average = 0.510561:
Info    : 0.00 < quality < 0.10 :      2581 elements
Info    : 0.10 < quality < 0.20 :      8133 elements
Info    : 0.20 < quality < 0.30 :     18621 elements
Info    : 0.30 < quality < 0.40 :     47492 elements
Info    : 0.40 < quality < 0.50 :     59893 elements
Info    : 0.50 < quality < 0.60 :     43653 elements
Info    : 0.60 < quality < 0.70 :     23898 elements
Info    : 0.70 < quality < 0.80 :     19238 elements
Info    : 0.80 < quality < 0.90 :     18728 elements
Info    : 0.90 < quality < 1.00 :      9516 elements
Info    : 8574 edge swaps, 2750 node relocations (volume = 2.42e+09): worst = 0.0329135 / average = 0.524359 (Wall 0.729399s, CPU 0.717532s)
Info    : 9790 edge swaps, 3941 node relocations (volume = 2.42e+09): worst = 0.0329135 / average = 0.5249 (Wall 1.32555s, CPU 1.31195s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :      1154 elements
Info    : 0.10 < quality < 0.20 :      4744 elements
Info    : 0.20 < quality < 0.30 :     12614 elements
Info    : 0.30 < quality < 0.40 :     47002 elements
Info    : 0.40 < quality < 0.50 :     59041 elements
Info    : 0.50 < quality < 0.60 :     44661 elements
Info    : 0.60 < quality < 0.70 :     24758 elements
Info    : 0.70 < quality < 0.80 :     19564 elements
Info    : 0.80 < quality < 0.90 :     18939 elements
Info    : 0.90 < quality < 1.00 :      9608 elements
Info    : Done optimizing mesh (Wall 3.10763s, CPU 3.06122s)
Info    : 93646 nodes 636165 elements
Info    : Writing 'mesh/pocket_transmon.msh'...
Info    : Done writing 'mesh/pocket_transmon.msh'

In [6]:
attributes_table

                    Name ID     Type
0                pad_top  1  Surface
1                pad_bot  2  Surface
2  readout_connector_pad  3  Surface
5              substrate  4   Volume
6                    air  5   Volume
3           ground_plane  6  Surface
4              far_field  7  Surface

## Xmon (Transmon Cross)

In [7]:
design = designs.DesignPlanar()
gui = MetalGUI(design)

## define qubit ##
qubit_options = dict(connection_pads=dict(claw = dict(connector_location = '90', connector_type = '0',claw_length="150um",claw_gap="4um")))
qubit = TransmonCross(design,'qubit',options=qubit_options)

gui.rebuild()
gui.autoscale()

In [11]:
design.qgeometry.tables["poly"]

,component,name,geometry,layer,subtract,helper,chip,fillet
0,1,cross,"POLYGON ((-0.2 -0.01, -0.2 0.01, -0.01 0.01, -...",1,False,False,main,NaN
1,1,cross_etch,"POLYGON ((-0.22 -0.03, -0.22 0.03, -0.03 0.03,...",1,True,False,main,NaN
2,1,claw_connector_arm,"POLYGON ((0.005 0.279, 0.005 0.239, 0.049 0.23...",1,False,False,main,NaN
3,1,claw_connector_etcher,"POLYGON ((0.009 0.283, 0.009 0.243, 0.053 0.24...",1,True,False,main,NaN

In [14]:
''' Mesh our Quantum Metal design '''

## define which components we want to give mesh attributes ##
Attributes = {"cross":1,"claw_connector_arm":2}

mesh_dir = "mesh/"
meshfile = "xmon.msh"
path_to_mesh = mesh_dir + meshfile

## mesh the design --> returns pandas.dataframe of labeled mesh attributes ##
## look at readthedocs, mesh_Quantum_Metal_design has a lot of flexibility to control surface mesh size, volume mesh size, substrate size, etc ## 
attributes_table = mesh.mesh_Quantum_Metal_design(design,output_mesh=path_to_mesh,Attributes=Attributes,surface_mesh_size=0.0005);

Info    : Meshing 1D...nts
Info    : [  0%] Meshing curve 25 (Line)
Info    : [ 10%] Meshing curve 26 (Line)
Info    : [ 10%] Meshing curve 27 (Line)
Info    : [ 10%] Meshing curve 28 (Line)
Info    : [ 10%] Meshing curve 29 (Line)
Info    : [ 10%] Meshing curve 30 (Line)
Info    : [ 10%] Meshing curve 31 (Line)
Info    : [ 20%] Meshing curve 32 (Line)
Info    : [ 20%] Meshing curve 33 (Line)
Info    : [ 20%] Meshing curve 34 (Line)
Info    : [ 20%] Meshing curve 35 (Line)
Info    : [ 20%] Meshing curve 36 (Line)
Info    : [ 20%] Meshing curve 49 (Line)
Info    : [ 20%] Meshing curve 50 (Line)
Info    : [ 30%] Meshing curve 51 (Line)
Info    : [ 30%] Meshing curve 52 (Line)
Info    : [ 30%] Meshing curve 53 (Line)
Info    : [ 30%] Meshing curve 54 (Line)
Info    : [ 30%] Meshing curve 55 (Line)
Info    : [ 30%] Meshing curve 56 (Line)
Info    : [ 30%] Meshing curve 57 (Line)
Info    : [ 40%] Meshing curve 58 (Line)
Info    : [ 40%] Meshing curve 59 (Line)
Info    : [ 40%] Meshing curve 60 (Line)
Info    : [ 40%] Meshing curve 61 (Line)
Info    : [ 40%] Meshing curve 62 (Line)
Info    : [ 40%] Meshing curve 63 (Line)
Info    : [ 40%] Meshing curve 64 (Line)
Info    : [ 50%] Meshing curve 65 (Line)
Info    : [ 50%] Meshing curve 66 (Line)
Info    : [ 50%] Meshing curve 67 (Line)
Info    : [ 50%] Meshing curve 68 (Line)
Info    : [ 50%] Meshing curve 69 (Line)
Info    : [ 50%] Meshing curve 70 (Line)
Info    : [ 60%] Meshing curve 71 (Line)
Info    : [ 60%] Meshing curve 72 (Line)
Info    : [ 60%] Meshing curve 73 (Line)
Info    : [ 60%] Meshing curve 74 (Line)
Info    : [ 60%] Meshing curve 75 (Line)
Info    : [ 60%] Meshing curve 76 (Line)
Info    : [ 60%] Meshing curve 77 (Line)
Info    : [ 70%] Meshing curve 78 (Line)
Info    : [ 70%] Meshing curve 79 (Line)
Info    : [ 70%] Meshing curve 80 (Line)
Info    : [ 70%] Meshing curve 81 (Line)
Info    : [ 70%] Meshing curve 82 (Line)
Info    : [ 70%] Meshing curve 83 (Line)
Info    : [ 70%] Meshing curve 84 (Line)
Info    : [ 80%] Meshing curve 85 (Line)
Info    : [ 80%] Meshing curve 86 (Line)
Info    : [ 80%] Meshing curve 87 (Line)
Info    : [ 80%] Meshing curve 88 (Line)
Info    : [ 80%] Meshing curve 89 (Line)
Info    : [ 80%] Meshing curve 90 (Line)
Info    : [ 80%] Meshing curve 91 (Line)
Info    : [ 90%] Meshing curve 92 (Line)
Info    : [ 90%] Meshing curve 93 (Line)
Info    : [ 90%] Meshing curve 94 (Line)
Info    : [ 90%] Meshing curve 95 (Line)
Info    : [ 90%] Meshing curve 96 (Line)
Info    : [ 90%] Meshing curve 97 (Line)
Info    : [ 90%] Meshing curve 98 (Line)
Info    : [100%] Meshing curve 99 (Line)
Info    : [100%] Meshing curve 100 (Line)
Info    : [100%] Meshing curve 101 (Line)
Info    : [100%] Meshing curve 102 (Line)
Info    : [100%] Meshing curve 103 (Line)
Info    : [100%] Meshing curve 104 (Line)
Info    : Done meshing 1D (Wall 3.22811s, CPU 3.18429s)
Info    : Meshing 2D...
Info    : [  0%] Meshing surface 13 (Plane, Frontal-Delaunay)
Info    : [ 10%] Meshing surface 15 (Plane, Frontal-Delaunay)
Info    : [ 20%] Meshing surface 16 (Plane, Frontal-Delaunay)
Info    : [ 30%] Meshing surface 17 (Plane, Frontal-Delaunay)
Info    : [ 30%] Meshing surface 18 (Plane, Frontal-Delaunay)
Info    : [ 40%] Meshing surface 19 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 20 (Plane, Frontal-Delaunay)
Info    : [ 50%] Meshing surface 21 (Plane, Frontal-Delaunay)
Info    : [ 60%] Meshing surface 22 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 23 (Plane, Frontal-Delaunay)
Info    : [ 70%] Meshing surface 24 (Plane, Frontal-Delaunay)
Info    : [ 80%] Meshing surface 25 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 26 (Plane, Frontal-Delaunay)
Info    : [ 90%] Meshing surface 27 (Plane, Frontal-Delaunay)
Info    : [100%] Meshing surface 28 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.906683s, CPU 0.896942s)
Info    : Meshing 3D...
Info    : 3D Meshing 2 volumes with 1 connected component
Info    : Tetrahedrizing 28670 nodes...
Info    : Done tetrahedrizing 28678 nodes (Wall 1.57955s, CPU 1.56135s)
Info    : Reconstructing mesh...
Info    :  - Creating surface mesh
Info    :  - Identifying boundary edges
Info    :  - Recovering boundary
Info    : Done reconstructing mesh (Wall 3.63581s, CPU 3.59547s)
Info    : Found volume 1
Info    : Found volume 2
Info    : It. 0 - 0 nodes created - worst tet radius 9.91056 (nodes removed 0 0)
Info    : It. 500 - 500 nodes created - worst tet radius 2.42786 (nodes removed 0 0)
Info    : It. 1000 - 1000 nodes created - worst tet radius 1.49315 (nodes removed 0 0)
Info    : It. 1500 - 1500 nodes created - worst tet radius 1.42742 (nodes removed 0 0)
Info    : It. 2000 - 2000 nodes created - worst tet radius 1.53383 (nodes removed 0 0)
Info    : It. 2500 - 2500 nodes created - worst tet radius 1.39783 (nodes removed 0 0)
Info    : It. 3000 - 3000 nodes created - worst tet radius 1.33254 (nodes removed 0 0)
Info    : It. 3500 - 3500 nodes created - worst tet radius 1.23897 (nodes removed 0 0)
Info    : It. 4000 - 3998 nodes created - worst tet radius 1.20124 (nodes removed 0 2)
Info    : It. 4500 - 4496 nodes created - worst tet radius 1.17217 (nodes removed 0 4)
Info    : It. 5000 - 4996 nodes created - worst tet radius 1.22026 (nodes removed 0 4)
Info    : It. 5500 - 5496 nodes created - worst tet radius 1.11372 (nodes removed 0 4)
Info    : It. 6000 - 5996 nodes created - worst tet radius 1.08881 (nodes removed 0 4)
Info    : It. 6500 - 6496 nodes created - worst tet radius 1.06524 (nodes removed 0 4)
Info    : It. 7000 - 6996 nodes created - worst tet radius 1.13778 (nodes removed 0 4)
Info    : It. 7500 - 7496 nodes created - worst tet radius 1.02395 (nodes removed 0 4)
Info    : It. 8000 - 7996 nodes created - worst tet radius 1.02602 (nodes removed 0 4)
Info    : 3D refinement terminated (37018 nodes total):
Info    :  - 68 Delaunay cavities modified for star shapeness
Info    :  - 4 nodes could not be inserted
Info    :  - 193458 tetrahedra created in 2.98798 sec. (64745 tets/s)
Info    : 1403 node relocations
Info    : Done meshing 3D (Wall 7.63173s, CPU 7.52248s)
Info    : Optimizing mesh...
Info    : Optimizing volume 1
Info    : Optimization starts (volume = 1.08216e+09) with worst = 0.00464887 / average = 0.477415:
Info    : 0.00 < quality < 0.10 :       572 elements
Info    : 0.10 < quality < 0.20 :      5351 elements
Info    : 0.20 < quality < 0.30 :     12400 elements
Info    : 0.30 < quality < 0.40 :     20640 elements
Info    : 0.40 < quality < 0.50 :     20629 elements
Info    : 0.50 < quality < 0.60 :     13172 elements
Info    : 0.60 < quality < 0.70 :      7534 elements
Info    : 0.70 < quality < 0.80 :      6682 elements
Info    : 0.80 < quality < 0.90 :      6532 elements
Info    : 0.90 < quality < 1.00 :      3207 elements
Info    : 3494 edge swaps, 1808 node relocations (volume = 1.08216e+09): worst = 0.067461 / average = 0.491888 (Wall 0.499646s, CPU 0.489695s)
Info    : 4249 edge swaps, 2619 node relocations (volume = 1.08216e+09): worst = 0.0680742 / average = 0.492785 (Wall 0.938364s, CPU 0.921177s)
Info    : 4439 edge swaps, 3093 node relocations (volume = 1.08216e+09): worst = 0.0680742 / average = 0.493029 (Wall 1.38302s, CPU 1.35702s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :        44 elements
Info    : 0.10 < quality < 0.20 :      3444 elements
Info    : 0.20 < quality < 0.30 :     10236 elements
Info    : 0.30 < quality < 0.40 :     20827 elements
Info    : 0.40 < quality < 0.50 :     20677 elements
Info    : 0.50 < quality < 0.60 :     13773 elements
Info    : 0.60 < quality < 0.70 :      8001 elements
Info    : 0.70 < quality < 0.80 :      6789 elements
Info    : 0.80 < quality < 0.90 :      6669 elements
Info    : 0.90 < quality < 1.00 :      3224 elements
Info    : Optimizing volume 2
Info    : Optimization starts (volume = 1.08216e+09) with worst = 0.00538331 / average = 0.47755:
Info    : 0.00 < quality < 0.10 :       577 elements
Info    : 0.10 < quality < 0.20 :      5346 elements
Info    : 0.20 < quality < 0.30 :     12389 elements
Info    : 0.30 < quality < 0.40 :     20635 elements
Info    : 0.40 < quality < 0.50 :     20619 elements
Info    : 0.50 < quality < 0.60 :     13206 elements
Info    : 0.60 < quality < 0.70 :      7538 elements
Info    : 0.70 < quality < 0.80 :      6631 elements
Info    : 0.80 < quality < 0.90 :      6579 elements
Info    : 0.90 < quality < 1.00 :      3219 elements
Info    : 3482 edge swaps, 1784 node relocations (volume = 1.08216e+09): worst = 0.067461 / average = 0.491888 (Wall 0.474634s, CPU 0.467982s)
Info    : 4227 edge swaps, 2593 node relocations (volume = 1.08216e+09): worst = 0.0680742 / average = 0.492782 (Wall 0.899141s, CPU 0.886921s)
Info    : 4399 edge swaps, 3065 node relocations (volume = 1.08216e+09): worst = 0.0680742 / average = 0.492984 (Wall 1.30771s, CPU 1.29138s)
Info    : No ill-shaped tets in the mesh :-)
Info    : 0.00 < quality < 0.10 :        43 elements
Info    : 0.10 < quality < 0.20 :      3451 elements
Info    : 0.20 < quality < 0.30 :     10285 elements
Info    : 0.30 < quality < 0.40 :     20849 elements
Info    : 0.40 < quality < 0.50 :     20658 elements
Info    : 0.50 < quality < 0.60 :     13758 elements
Info    : 0.60 < quality < 0.70 :      8031 elements
Info    : 0.70 < quality < 0.80 :      6734 elements
Info    : 0.80 < quality < 0.90 :      6700 elements
Info    : 0.90 < quality < 1.00 :      3254 elements
Info    : Done optimizing mesh (Wall 2.82213s, CPU 2.7772s)
Info    : 37018 nodes 252266 elements
Info    : Writing 'mesh/xmon.msh'...
Info    : Done writing 'mesh/xmon.msh'

In [13]:
attributes_table

                 Name ID     Type
0               cross  1  Surface
1  claw_connector_arm  2  Surface
4           substrate  3   Volume
5                 air  4   Volume
2        ground_plane  5  Surface
3           far_field  6  Surface